In [2]:
# setup 
import pandas as pd 
import numpy as np 
tutorLogDF = pd.read_csv("raw data/tutor_log.tsv", delimiter="\t", index_col=False)

/var/folders/jk/t2z3d3zd447g4wlv0rvml1400000gn/T/ipykernel_87893/591765958.py:4: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  tutorLogDF = pd.read_csv("raw data/tutor_log.tsv", delimiter="\t", index_col=False)

Here we explore what values each column can take:

In [ ]:
maxLength = 10
for colName in tutorLogDF.columns: 
    col = tutorLogDF[colName]
    print("For column *", colName, "* the unique values are: ")
    if(len(pd.unique(col)) < maxLength): 
        print(pd.unique(col))
    else: 
        # if length is too long, going to omit some values 
        print(pd.unique(col)[0:maxLength])
        print(" ... ")
    print()

For column * Row * the unique values are:
[ 1  2  3  4  5  6  7  8  9 10]
 ...

For column * Sample Name * the unique values are:
['All Data']

For column * Transaction Id * the unique values are:
['214c0968185c01987dec7dfce9008aee' 'b18b30cdfc8347e628472e8160abf65f'
 '1f67330d3a74a99a0ddd2981e562485d' '3044ad2c1b0c3ad0831cdb391b1629d5'
 'c1a8e97dfefd2f7fa7aa0776120fb321' '779e1ccde6baaa77ec165503bf93ba3e'
 'b96a94861cd94e091f96aa9427602570' 'd07f1e4af72386e5b840e3d67bcf5f37'
 '8d4941963e71c8ef89f0330abbf360dd' '078e39be49c253f5c5f7f9d7f3ccf16f']
 ...

For column * Anon Student Id * the unique values are:
['Stu_011924479d5e1be392bb55cb21567c3f'
 'Stu_033eed4283afcc99a64251fc5388d824'
 'Stu_03cac10de8d282be297f7b1550ef153d'
 'Stu_03cbefeff126eab919081d0a505555d0'
 'Stu_064567c1ccf2d7da2dfbcd94e7bb57a9'
 'Stu_08d66b3d398409412db22b6d514aa6da'
 'Stu_0970273addcc362e28e73fd97b203527'
 'Stu_14053def54d0fd78ad49613e7bca6e70'
 'Stu_1b58811bce4e1e0b46297dc353138a80'
 'Stu_21faa7fce14fa69f7683c1c9371e5456']
 ...

For column * Session Id * the unique values are:
['Sdc467a8b53256d2176a78ed340385cd0' 'S39bbae53a7cadf1f24f29c5339398dd0'
 'S1bedb39ceccbf21cde19f098c7aebff0' 'S9ff154ee5e97df76c04e1580ff6abf6d'
 'S0338bfd18add716e5695c757bb1ff879' 'S4f09da6e5dbc4aa89cd525f7f596c615'
 'S73e50e07d4394f1751daa59751fee007' 'Se7b8bd737e22769969c3b1f8fd974119'
 'Sd22d983502efc7ee0e52720f95738e60' 'S52718c253ee665b3447cdc3b07c4e1ca']
 ...

For column * Time * the unique values are:
['2022-05-23 14:20:22' '2022-05-23 14:21:20' '2022-05-23 14:21:46'
 '2022-05-23 14:21:50' '2022-05-23 14:22:11' '2022-05-23 14:22:14'
 '2022-05-23 14:22:18' '2022-05-23 14:22:28' '2022-05-23 14:22:46'
 '2022-05-23 14:22:57']
 ...

For column * Time Zone * the unique values are:
['America/New_York' 'UTC']

For column * Duration (sec) * the unique values are:
['0' '14.5' '26' '5.25' '3' '0.5' '3.333' '9' '3.667' '2']
 ...

For column * Student Response Type * the unique values are:
['ATTEMPT' 'HINT_REQUEST']

For column * Student Response Subtype * the unique values are:
['tutor-performed' nan]

For column * Tutor Response Type * the unique values are:
[nan 'RESULT' 'HINT_MSG']

For column * Tutor Response Subtype * the unique values are:
[nan]

For column * Level (Assignment) * the unique values are:
['blue' 'red' nan]

For column * Level (Package) * the unique values are:
['LynnetteDiagrams-3-29-22' 'Diagram Benefits Tutorial' nan]

For column * Level (ProblemSet) * the unique values are:
['Lynnette Blue Level 1' 'Lynnette Blue Level 2' 'Lynnette Blue Level 3'
 'Lynnette Blue Level 4' 'Lynnette Red Level 0' 'Lynnette Red Level 1'
 'Lynnette Red Level 2' 'Lynnette Red Level 3' 'Lynnette Red Level 4'
 'Lynnette Red Level 5']
 ...

For column * Level (Position) * the unique values are:
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 ...

For column * Level (Page) * the unique values are:
[nan 'ClassDashboard']

For column * Problem Name * the unique values are:
['xplus2eq6 Diagrams Choice' '5plusxeq7-diagrams-choice'
 '8eqxplus3 Diagrams Choice' '7eq2plusx Diagrams Choice'
 '2xplus3eq7 Diagrams Choice' '3xplus1eq10 Diagrams Choice'
 '7plus2xeq11 Diagrams Choice' '1plus2xeq5 Diagrams Choice'
 '4xplus3eq11 Diagrams Choice' '8eq3plus5x Diagrams Choice']
 ...

For column * Problem View * the unique values are:
[ 1.  2.  3.  4. nan]

For column * Problem Start Time * the unique values are:
['2022-05-23 14:20:22' '2022-05-23 14:21:50' '2022-05-23 14:22:17'
 '2022-05-23 14:23:03' '2022-05-23 14:23:41' '2022-05-23 14:26:37'
 '2022-05-23 14:34:50' '2022-05-24 14:03:56' '2022-05-24 14:06:23'
 '2022-05-24 14:09:58']
 ...

For column * Step Name * the unique values are:
[nan 'solve1 UpdateTextField' 'groupExplain1Diagrams UpdateRadioButton'
 'done ButtonPressed' 'diagramsButton ButtonPressed'
 'solve2 UpdateTextField' 'solve3 UpdateTextField'
 'groupExplain3Diagrams UpdateRadioButton'
 'groupExplain2Diagrams UpdateRadioButton'
 'groupExplain0Diagrams UpdateRadioButton']
 ...

For column * Attempt At Step * the unique values are:
[nan  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 ...

For column * Is Last Attempt * the unique values are:
[nan  1.  0.]

For column * Outcome * the unique values are:
[nan 'CORRECT' 'INCORRECT' 'HINT']

For column * Selection * the unique values are:
['diagramsButton' '_root' 'solve1' 'groupExplain1Diagrams' 'done' 'solve2'
 'solve3' 'groupExplain3Diagrams' 'groupExplain2Diagrams' 'nextButton']
 ...

For column * Selection.1 * the unique values are:
[nan 'hint' 'solve2' 'solve4' 'solve1' 'solve5' 'solve3'
 'popupCloseButton' 'solve6' 'hintButton']
 ...

For column * Action * the unique values are:
['setEnabled' 'showNextRow' 'UpdateTextField' 'UpdateRadioButton'
 'showStepInputs' 'ButtonPressed' 'showDiagrams' 'setStepDiagrams'
 'visibilityChange' 'SetVisible']
 ...

For column * Action.1 * the unique values are:
[nan 'PreviousFocus']

For column * Input * the unique values are:
['true' 'arg' 'x = 4'
 'subtraction,2:                                                                                                                                          x                     2                                                                                    2                                                           4                     2                                                                                    2'
 '-1'
 'subtraction,5:                                                                                                                                          5                     x                                                                                    5                                                           5                     2                                                                                    5'
 'x = 2' nan '8 = x+3,subtraction,3'
 'subtraction,3:                                                                                                                                          5                     3                                                                                    3                                                           x                     3                                                                                    3']
 ...

For column * Feedback Text * the unique values are:
[nan
 'Good job!  You subtracted 2 from both sides of the equation to isolate the variable.'
 'Good job!  You subtracted 5 from both sides of the equation to isolate the variable.'
 'Good job!  You subtracted 3 from both sides of the equation to isolate the variable.'
 'Yes, that is correct, but you are skipping too many steps. Can you go step-by-step?'
 "I'm sorry, but you are not done yet. Please continue working."
 'Good job!  You divided both sides of the equation by 2'
 'Good job!  You subtracted 1 from both sides of the equation to isolate the variable.'
 'You are missing an equals sign.  Make sure to type in the entire equation.'
 'Now type in the step shown in the diagram you picked']
 ...

For column * Feedback Classification * the unique values are:
[nan]

For column * Help Level * the unique values are:
[nan  1.  2.  3.  4.]

For column * Total Num Hints * the unique values are:
[nan  3.  2.  4.  1.]

For column * Condition Name * the unique values are:
['none']

For column * Condition Type * the unique values are:
['none']

For column * KC (Default) * the unique values are:
[nan 'cancel-const' 'division-simple' 'divide' 'subtraction-const'
 'combine-like-const' 'subtraction-var' 'combine-like-var' 'cancel-var'
 'distribute-division']
 ...

For column * KC Category (Default) * the unique values are:
[nan 'simplification' 'transformation']

For column * KC (Default).1 * the unique values are:
[nan 'combine-like-const' 'division-simple' 'combine-like-var' 'divide'
 'subtraction-var' 'subtraction-const']

For column * KC Category (Default).1 * the unique values are:
[nan 'simplification' 'transformation']

For column * KC (Default).2 * the unique values are:
[nan 'subtraction-const' 'subtraction-var' 'division-complex']

For column * KC Category (Default).2 * the unique values are:
[nan 'transformation']

For column * KC (Single-KC) * the unique values are:
[nan 'Single-KC']

For column * KC Category (Single-KC) * the unique values are:
[nan]

For column * KC (Unique-step) * the unique values are:
[nan 'KC20' 'KC485' 'KC212' 'KC477' 'KC320' 'KC475' 'KC255' 'KC151'
 'KC209']
 ...

For column * KC Category (Unique-step) * the unique values are:
[nan]

For column * School * the unique values are:
['Wyoming Valley West 7th']

For column * Class * the unique values are:
['Period3' 'Period7' 'Period1' 'Period4' 'Period5']

For column * CF (Completion History) * the unique values are:
[nan '0,0,0,0' '1,0,0,0' '1,1,0,0' '1,1,1,0' '0,0,0' '1,0,0' '1,1,0'
 '0,0,0,0,0' '1,0,0,0,0']
 ...

For column * CF (Team ID) * the unique values are:
[nan 'jFAEDQfQB7XSX01Gj/03FKbttsM=' 'lgq7ezp4IDsQUF8xie5s0dUdo0w='
 'djZv3A9SwOIgged8Zd3XN6iJei4=' '8k+JPa2e+aH3LdvKu7eQbWoo184='
 'f1JFHTQ1YXtukAa8jGE1R0YWj48=' 'ZnfNrudUBGtVo3p/VHl4Kqd0uCI='
 'W82N8ks5+r1us1JW+SfvXQQNYQY=' 'FHB91wa3Nt1YdKtLVdHgCFYoJlo='
 '/jxd6wVXpIMBgZN9NOaYZcuWu+I=']
 ...

For column * CF (Team Position) * the unique values are:
[nan '1 of 1']

For column * CF (problem_context) * the unique values are:
[nan  1.  2.  3.  4.  5.]

For column * CF (rules) * the unique values are:
[nan
 'focusSolutionStep,addSubtractSimpleTerm,simplifyForAbstractSearch,writeAbstract,addSubtractSimpleTerm,CancelOrCombineLikeTerms,CancelOrCombineLikeTerms,write,EndGenStepDiagrams'
 'PickDiagram' 'done' 'ShowDiagrams'
 'focusSolutionStep,divideByXCoefficient,simplifyForAbstractSearch,writeAbstract,divideByXCoefficient,write'
 'focusSolutionStep,simplifyForAbstractSearch,writeAbstract,Divide,Divide,write,EndGenStepDiagrams'
 'focusSolutionStep,addSubtractSimpleTerm'
 'focusSolutionStep,divideByXCoefficient,simplifyForAbstractSearch,writeAbstract,divideByXCoefficient,Divide,Divide,write,EndGenStepDiagrams'
 'focusSolutionStep,addSubtractSimpleTerm,simplifyForAbstractSearch,writeAbstract,addSubtractSimpleTerm,write']
 ...

For column * CF (step_id) * the unique values are:
[nan 'solve1 UpdateTextField' 'groupExplain1Diagrams UpdateRadioButton'
 'done ButtonPressed' 'diagramsButton ButtonPressed'
 'solve2 UpdateTextField' 'solve3 UpdateTextField'
 'groupExplain3Diagrams UpdateRadioButton'
 'groupExplain2Diagrams UpdateRadioButton'
 'groupExplain0Diagrams UpdateRadioButton']
 ...

For column * CF (tool_event_time) * the unique values are:
['2022-05-23 14:20:22.170 UTC' '2022-05-23 14:20:22.159 UTC'
 '2022-05-23 14:21:20.454 UTC' '2022-05-23 14:21:20.615 UTC'
 '2022-05-23 14:21:20.682 UTC' '2022-05-23 14:21:20.675 UTC'
 '2022-05-23 14:21:46.453 UTC' '2022-05-23 14:21:50.647 UTC'
 '2022-05-23 14:21:50.655 UTC' '2022-05-23 14:22:11.660 UTC']
 ...

For column * CF (tutor_event_time) * the unique values are:
[nan '2022-05-23 14:21:20.706 UTC' '2022-05-23 14:21:20.778 UTC'
 '2022-05-23 14:21:46.490 UTC' '2022-05-23 14:22:11.820 UTC'
 '2022-05-23 14:22:11.752 UTC' '2022-05-23 14:22:14.204 UTC'
 '2022-05-23 14:22:28.578 UTC' '2022-05-23 14:22:46.570 UTC'
 '2022-05-23 14:22:57.251 UTC']
 ...

For column * CF (tutor_input) * the unique values are:
[nan 'x = 4'
 'subtraction,2:                                                                                                                                          x                     2                                                                                    2                                                           4                     2                                                                                    2'
 '-1'
 'subtraction,5:                                                                                                                                          5                     x                                                                                    5                                                           5                     2                                                                                    5'
 'x = 2'
 'subtraction,3:                                                                                                                                          5                     3                                                                                    3                                                           x                     3                                                                                    3'
 'x = 5'
 'subtraction,2:                                                                                                                                          2                     5                                                                                    2                                                           2                     x                                                                                    2'
 'subtraction,3:                                                                                                                                          2x                     3                                                                                    3                                                           4                     3                                                                                    3']
 ...

For column * Event Type * the unique values are:
[nan]

We can use the column `Action` as an indicator of event. `Actor` can be found with `Anon User ID`, and `subject` is not really of relevance here. `Timestamp` can be converted from `Time` column. `Outcome` column can be indicator of correctness of student attempt and help-seeking behavior.

Note: 

- Value `hint` in `outcome` column can also be counted as incorrect attempt
- Understand hierachy of data/KC's (problems, steps, and transactions). Their definitions 
- `Duration` definition 
- Find out of Datashop can help coming up with summary stats

Potential RQ's: 
- Do students undergo more struggle when understanding certain KC's
- Does teacher help focus on particular KC's 

TODO: 
- Validate with observation log on period start/end time
- Validate with obsrevation log on students 
- data mine student performance, correctness of in-system responses DONE
- data mine number of hints DONE
- data mine time taken to solve (mean, std) DONE
- data mine total number of problems solved DONE
- data mine total KC level performance DONE
- data mine struggle from Kexin's paper 
- do some basic statistical tests to see how these variables relate to the learning gain (post-pre)/(1-pre)

Notes w/ Kexin: 
- Validate correspondence between *response types*: student attempt and tutuor display result, student asking for hint and tutor display hint 
- One assignment can have multiple levels. Level is hierrachial increasing by difficulty.